import { Package } from '../types/package';
const packageData: Package[] = [
  {
    customerName: 'Janet Adebayo',
    orderTime: '12 Aug 2022 - 12:25 am',
    checkInDate: '12 Aug - 17 Aug',
    trackingID: '9348fjr73',
    orderValue: 3500,
    hotelName: 'Kanak Villa Homestay',
    status: 'Paid',
  },
  {
    customerName: 'Adeola Oluwakemi',
    orderTime: '12 Aug 2022 - 12:25 am',
    checkInDate: '12 Aug - 17 Aug',
    trackingID: '9348fjr73',
    orderValue: 3500,
    hotelName: 'Kanak Villa Homestay',
    status: 'Cancelled by User',
  },

  {
    customerName: 'John Doe',
    orderTime: '15 Aug 2022 - 10:30 am',
    checkInDate: '20 Aug - 25 Aug',
    trackingID: '1234abc56',
    orderValue: 4000,
    hotelName: 'Ocean View Resort',
    status: 'Departured',
  },
  {
    customerName: 'Jane Smith',
    orderTime: '18 Aug 2022 - 2:00 pm',
    checkInDate: '22 Aug - 27 Aug',
    trackingID: '7890def12',
    orderValue: 4500,
    hotelName: 'Mountain Peak Hotel',
    status: 'Unpaid',
  },
  {
    customerName: 'Robert Johnson',
    orderTime: '21 Aug 2022 - 6:00 pm',
    checkInDate: '26 Aug - 31 Aug',
    trackingID: '3456ghi78',
    orderValue: 5000,
    hotelName: 'City Central Inn',
    status: 'Cancelled by User',
  },
  {
    customerName: 'Emily Davis',
    orderTime: '24 Aug 2022 - 9:00 am',
    checkInDate: '29 Aug - 3 Sep',
    trackingID: '9012jkl34',
    orderValue: 5500,
    hotelName: 'Country Side B&B',
    status: 'Unpaid',
  },
  {
    customerName: 'Michael Miller',
    orderTime: '27 Aug 2022 - 1:00 pm',
    checkInDate: '1 Sep - 6 Sep',
    trackingID: '5678mno90',
    orderValue: 6000,
    hotelName: 'Lakefront Cabins',
    status: 'Departured',
  },
  {
    customerName: 'Sarah Brown',
    orderTime: '30 Aug 2022 - 5:00 pm',
    checkInDate: '4 Sep - 9 Sep',
    trackingID: '2345pqr67',
    orderValue: 6500,
    hotelName: 'Desert Sands Motel',
    status: 'Unpaid',
  },
  {
    customerName: 'James Wilson',
    orderTime: '2 Sep 2022 - 8:00 am',
    checkInDate: '7 Sep - 12 Sep',
    trackingID: '8901stu23',
    orderValue: 7000,
    hotelName: 'Forest Hideaway',
    status: 'Paid',
  },
  {
    customerName: 'Patricia Moore',
    orderTime: '5 Sep 2022 - 12:00 pm',
    checkInDate: '10 Sep - 15 Sep',
    trackingID: '4567vwx89',
    orderValue: 7500,
    hotelName: 'Island Paradise Resort',
    status: 'Unpaid',
  },
  {
    customerName: 'William Taylor',
    orderTime: '8 Sep 2022 - 4:00 pm',
    checkInDate: '13 Sep - 18 Sep',
    trackingID: '0123yzab45',
    orderValue: 8000,
    hotelName: 'Sky High Hotel',
    status: 'Paid',
  },
  {
    customerName: 'Linda Anderson',
    orderTime: '11 Sep 2022 - 7:00 am',
    checkInDate: '16 Sep - 21 Sep',
    trackingID: '6789cdef01',
    orderValue: 8500,
    hotelName: 'Riverfront Lodge',
    status: 'Cancelled by User',
  },
];
export default packageData;
